version: "{build}"
build: off
install:
  - cmd: 'mkdir "C:\Users\appveyor\bin" || cmd /c "exit /b 0"'
  - cmd: SET PATH=C:\Users\appveyor\bin;%PATH%
  - cmd: curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.exe -o C:\Users\appveyor\bin\boot.exe
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.boot\cache
  - C:\Users\appveyor\bin
test_script:
  - boot test
